#use official node image as base image
FROM node:20-alpine3.16

#specify working directory
WORKDIR /app

#copy package.json to working directory , if the package.json is more than 1, use COPY package*.json ./
COPY package*.json ./

#install dependencies
RUN npm install

#copy the source code
COPY . .

#expose port
EXPOSE 5000

#start the application
CMD ["node" , "index.js"]


